### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED when precompiling CuArrays

### ISSUE THREAD

**Issue by wehlutyk** [JuliaGPU/CuArrays.jl#156]
I recently stumbled upon Flux.jl and am evaluating switching from Tensorflow to Julia full time, which brought me here.

I get the following error when trying to use CuArrays:

```bash
slerique@k80alpha:/scratch/slerique$ env
CONDA_SHLVL=0
LC_ALL=en_US.utf8
LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64
LANG=en_US.utf8
JULIA_DEPOT_PATH=/scratch/slerique/.julia
MODULE_VERSION=3.2.10
PWD=/scratch/slerique
HOME=/home/slerique
LOADEDMODULES=cuda/9.0
SHELL=/bin/bash
SHLVL=1
LANGUAGE=en_US.utf8
MANPATH=/usr/local/cuda-9.0/man:/usr/share/man
MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/Modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
LOGNAME=slerique
MODULE_VERSION_STACK=3.2.10
PATH=/usr/local/cuda-9.0/bin:/home/slerique/.cargo/bin:/home/slerique/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
_LMFILES_=/usr/share/modules/modulefiles/cuda/9.0
MODULESHOME=/usr/local/cuda-9.0
BASH_FUNC_module%%=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/usr/bin/env
OLDPWD=/scratch
slerique@k80alpha:/scratch/slerique$ rm -rf .julia
slerique@k80alpha:/scratch/slerique$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.0) pkg> add CuArrays
   Cloning default registries into /scratch/slerique/.julia/registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
  Updating registry at `/scratch/slerique/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Conda ──────────────── v1.0.2
 Installed DiffRules ──────────── v0.0.7
 Installed Adapt ──────────────── v0.3.1
 Installed GPUArrays ──────────── v0.4.2
 Installed MacroTools ─────────── v0.4.4
 Installed NNlib ──────────────── v0.4.2
 Installed BinaryProvider ─────── v0.5.1
 Installed CuArrays ───────────── v0.8.0
 Installed LLVM ───────────────── v0.9.15
 Installed URIParser ──────────── v0.4.0
 Installed FillArrays ─────────── v0.2.1
 Installed Compat ─────────────── v1.2.0
 Installed Requires ───────────── v0.5.2
 Installed NaNMath ────────────── v0.3.2
 Installed ForwardDiff ────────── v0.9.0
 Installed CUDAapi ────────────── v0.5.2
 Installed VersionParsing ─────── v1.1.3
 Installed JSON ───────────────── v0.19.0
 Installed DiffResults ────────── v0.0.3
 Installed CommonSubexpressions ─ v0.2.0
 Installed CUDAdrv ────────────── v0.8.6
 Installed FFTW ───────────────── v0.2.4
 Installed Reexport ───────────── v0.2.0
 Installed SpecialFunctions ───── v0.7.1
 Installed AbstractFFTs ───────── v0.3.2
 Installed CUDAnative ─────────── v0.9.1
 Installed BinDeps ────────────── v0.8.10
 Installed StaticArrays ───────── v0.8.3
  Updating `/scratch/slerique/.julia/environments/v1.0/Project.toml`
  [3a865a2d] + CuArrays v0.8.0
  Updating `/scratch/slerique/.julia/environments/v1.0/Manifest.toml`
  [621f4979] + AbstractFFTs v0.3.2
  [79e6a3ab] + Adapt v0.3.1
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.1
  [3895d2a7] + CUDAapi v0.5.2
  [c5f51814] + CUDAdrv v0.8.6
  [be33ccc6] + CUDAnative v0.9.1
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v1.2.0
  [8f4d0f93] + Conda v1.0.2
  [3a865a2d] + CuArrays v0.8.0
  [163ba53b] + DiffResults v0.0.3
  [b552c78f] + DiffRules v0.0.7
  [7a1cc6ca] + FFTW v0.2.4
  [1a297f60] + FillArrays v0.2.1
  [f6369f11] + ForwardDiff v0.9.0
  [0c68f7d7] + GPUArrays v0.4.2
  [682c06a0] + JSON v0.19.0
  [929cbde3] + LLVM v0.9.15
  [1914dd2f] + MacroTools v0.4.4
  [872c559c] + NNlib v0.4.2
  [77ba4419] + NaNMath v0.3.2
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v0.5.2
  [276daf66] + SpecialFunctions v0.7.1
  [90137ffa] + StaticArrays v0.8.3
  [30578b45] + URIParser v0.4.0
  [81def892] + VersionParsing v1.1.3
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
  Building SpecialFunctions → `/scratch/slerique/.julia/packages/SpecialFunctions/sXbz6/deps/build.log`
  Building CUDAdrv ─────────→ `/scratch/slerique/.julia/packages/CUDAdrv/LC5XS/deps/build.log`
  Building LLVM ────────────→ `/scratch/slerique/.julia/packages/LLVM/mcS4Y/deps/build.log`
  Building CUDAnative ──────→ `/scratch/slerique/.julia/packages/CUDAnative/AGfq2/deps/build.log`
  Building Conda ───────────→ `/scratch/slerique/.julia/packages/Conda/hsaaN/deps/build.log`
  Building FFTW ────────────→ `/scratch/slerique/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building CuArrays ────────→ `/scratch/slerique/.julia/packages/CuArrays/clDeS/deps/build.log`

julia> using CuArrays
[ Info: Precompiling CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae]
ERROR: InitError: CUDNNError(code 1, CUDNN_STATUS_NOT_INITIALIZED)
Stacktrace:
 [1] macro expansion at /scratch/slerique/.julia/packages/CuArrays/clDeS/src/dnn/error.jl:19 [inlined]
 [2] cudnnCreate at /scratch/slerique/.julia/packages/CuArrays/clDeS/src/dnn/libcudnn.jl:10 [inlined]
 [3] __init__() at /scratch/slerique/.julia/packages/CuArrays/clDeS/src/dnn/CUDNN.jl:15
 [4] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:627
 [5] _require_from_serialized(::String) at ./loading.jl:678
 [6] _require(::Base.PkgId) at ./logging.jl:317
 [7] require(::Base.PkgId) at ./loading.jl:852
 [8] macro expansion at ./logging.jl:311 [inlined]
 [9] require(::Module, ::Symbol) at ./loading.jl:834
during initialization of module CUDNN

julia> 
```

The cuDNN docs [state](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnCreate) that the error means `No compatible GPU found, CUDA driver not installed or disabled, CUDA runtime API initialization failed. ` However I'm able to run a hello world matrix multiplication on Tensorflow, using the google-provided wheel with GPU support (which I believe requires a working cuDNN):

```bash
slerique@k80alpha:/scratch/slerique/Code/nw2vec$ conda activate base36-cbpgpu
(base36-cbpgpu) slerique@k80alpha:/scratch/slerique/Code/nw2vec$ ipython
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf

In [2]: A = tf.ones((3, 5))

In [3]: b = tf.ones((5, 1))

In [4]: sess = tf.Session()
2018-10-08 13:53:42.885495: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-08 13:53:42.968861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-08 13:53:42.969163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:08.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-10-08 13:53:42.969192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-08 13:53:43.211595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-08 13:53:43.212410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-10-08 13:53:43.212427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-10-08 13:53:43.212659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10744 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:08.0, compute capability: 3.7)

In [5]: sess.run(A @ b)
Out[5]: 
array([[5.],
       [5.],
       [5.]], dtype=float32)

In [6]: 
```

(where `base36-cbpgpu` is [this](https://github.com/ixxi-dante/nw2vec/blob/master/environment.lock-cbpgpu.yml) environment.)

So:
* I have a compatible GPU (K80)
* I have a working CUDA installation under Tensorflow, which supposedly also involves cuDNN working
* julia finds both CUDA and cuDNN (which are in different places -- detailed log [here for CUDA](https://gist.github.com/fa3610ae923ab8e895cd03af05191719) and [here for cuDNN](https://gist.github.com/3a694fb4cd5671d98ba85a606cae326f).

I've searched through and through for what I might be missing, but can't seem to find it. Is this normal/expected behaviour, and might my setup have problem, or is this a bug?

**Comment by maleadt** [comment]
`dlopen("libcudnn")'` might be referring to a different library that we are using. Could you check `/scratch/slerique/.julia/packages/CuArrays/clDeS/deps/ext.jl`, which should contain the paths to the relevant libraries? You could also try to replicate the `cudnnCreate` call manually to reduce the test case and figure out what's happening (can help you with that).

**Comment by wehlutyk** [comment]
(I don't know what the next step in figuring out what's happening would be)

**Comment by maleadt** [comment]
`libcuda` is loaded by CUDAdrv.jl, so look for the `ext.jl` in that package's folder.
Do you know if the same shared libraries are being used by TensorFlow?

**Comment by wehlutyk** [comment]
`/scratch/slerique/.julia/packages/CUDAdrv/LC5XS/deps/ext.jl`:

```julia
# autogenerated file, do not edit
const libcuda_path = "/usr/lib/x86_64-linux-gnu/libcuda.so"
const libcuda_version = v"9.0.0"
const configured = true
const libcuda_vendor = "NVIDIA"
```

It turns out my TensorFlow test case was not relying on cuDNN, as a colleague (@jaklevab) is hitting the same error with a CNN model in TensorFlow now. The libs loaded (also found with `LD_DEBUG=libs`) are the same, and indeed there seems to be a problem with the CUDA/cuDNN setup on these machines (libcuda should be coming from `/usr/local/cuda-9.0/...`).

Can we leave this open for a few more days until I get things sorted with the sysadmin and check that it clears the problem? Many thanks for the help in debugging.

**Comment by maleadt** [comment]
> Can we leave this open for a few more days until I get things sorted with the sysadmin and check that it clears the problem?

Sure. For now, you could just download your own copy of a compatible `libcudnn` and put its path in CuArray's `ext.jl`. Could also be a useful debugging step (eg. your sysadmin might have installed an incompatible version of CUDNN).

**Comment by wehlutyk** [comment]
Thanks for the suggestions. It seems the problem was indeed that the version of cuDNN was incompatible with the CUDA version installed. It's fixed and working, so thanks again for helping me debug this!
