### ISSUE TITLE
CUDNN Batchnorm fails 

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaGPU/CuArrays.jl#531]
**Describe the bug**
Batchnorm operations throw an error due to `CUDNNError(code CUDNN_STATUS_BAD_PARAM, CUDNN_STATUS_BAD_PARAM)`

This is probably an error on my side given that the tests don't pass on my machine, but I don't know what to do to debug.

* OS: Windows 10
* GPU : RTX 2080Ti
* Driver: 441.21 and 441.41
* CUDA: 10.2.0 (according to CUDAdrv) 

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
using CuArrays

]test
# Stuff, but no warnings.  Full output: https://gist.github.com/DrChainsaw/1dc5187245fa86a7888953430d931af2
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays E:\Programs\julia\.julia\packages\GPUArrays\1wgPO\src\indexing.jl:16
[ Info: Testing CUDNN 7.4.1
Batchnorm: Error During Test at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\dnn.jl:83
  Got exception outside of a @test
  CUDNNError(code CUDNN_STATUS_BAD_PARAM, CUDNN_STATUS_BAD_PARAM)
  Stacktrace:
   [1] cudnnBatchNormalizationForwardInference(::Ptr{Nothing}, ::CuArrays.CUDNN.cudnnBatchNormMode_t, ::Base.RefValue{Float32}, ::Base.RefValue{Float32}, ::CuArrays.CUDNN.TensorDesc, ::CuArray{Float32,4,CuArray{Float32,2,Nothing}}, ::CuArrays.CUDNN.TensorDesc, ::CuArray{Float32,4,Nothing}, ::CuArrays.CUDNN.TensorDesc, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::Float32) at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\src\dnn\error.jl:19
   [2] #cudnnBNForward!#344(::Nothing, ::Float32, ::Float32, ::Float32, ::Bool, ::typeof(CuArrays.CUDNN.cudnnBNForward!), ::CuArray{Float32,4,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,4,CuArray{Float32,2,Nothing}}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::Float64) at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\src\dnn\batchnorm.jl:62
   [3] #cudnnBNForward! at .\none:0 [inlined]
   [4] #batchnorm#343 at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\src\dnn\batchnorm.jl:26 [inlined]
   [5] #batchnorm at .\none:0 [inlined]
   [6] #batchnorm#342(::Nothing, ::Float32, ::Float32, ::Float32, ::Bool, ::typeof(CuArrays.CUDNN.batchnorm), ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,2,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::Float64) at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\src\dnn\batchnorm.jl:17
   [7] (::CuArrays.CUDNN.var"#kw##batchnorm")(::NamedTuple{(:training,),Tuple{Bool}}, ::typeof(CuArrays.CUDNN.batchnorm), ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,2,Nothing}, ::CuArray{Float32,1,Nothing}, ::CuArray{Float32,1,Nothing}, ::Float64) at .\none:0
   [8] top-level scope at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\dnn.jl:87
   [9] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
   [10] top-level scope at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\dnn.jl:84
   [11] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
   [12] top-level scope at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\dnn.jl:3
   [13] include at .\boot.jl:328 [inlined]
   [14] include_relative(::Module, ::String) at .\loading.jl:1105
   [15] include(::Module, ::String) at .\Base.jl:31
   [16] include(::String) at .\client.jl:424
   [17] top-level scope at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\runtests.jl:39
   [18] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
   [19] top-level scope at E:\Programs\julia\.julia\packages\CuArrays\ZYCpV\test\runtests.jl:27
   [20] include at .\boot.jl:328 [inlined]
   [21] include_relative(::Module, ::String) at .\loading.jl:1105
   [22] include(::Module, ::String) at .\Base.jl:31
   [23] include(::String) at .\client.jl:424
   [24] top-level scope at none:6
   [25] eval(::Module, ::Any) at .\boot.jl:330
   [26] exec_options(::Base.JLOptions) at .\client.jl:263
   [27] _start() at .\client.jl:460
```

**Expected behavior**
Batchnorm should work

**Build log**
```
julia> Pkg.build()
  Building SpecialFunctions → `E:\Programs\julia\.julia\packages\SpecialFunctions\ne2iw\deps\build.log`
  Building MbedTLS ─────────→ `E:\Programs\julia\.julia\packages\MbedTLS\a1JFn\deps\build.log`
  Building WebIO ───────────→ `E:\Programs\julia\.julia\packages\WebIO\2mZPb\deps\build.log`
  Building CodecZlib ───────→ `E:\Programs\julia\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building Conda ───────────→ `E:\Programs\julia\.julia\packages\Conda\kLXeC\deps\build.log`
  Building FFTW ────────────→ `E:\Programs\julia\.julia\packages\FFTW\MJ7kl\deps\build.log`
  Building ZipFile ─────────→ `E:\Programs\julia\.julia\packages\ZipFile\oD4uG\deps\build.log`
false
```

**Environment details (please complete this section)**
Details on Julia:
```julia
versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

Julia packages:
```julia
]status
    Status `E:\Programs\julia\.julia\environments\v1.3\Project.toml`
  [c52e3926] Atom v0.11.3
  [3a865a2d] CuArrays v1.5.0
  [587475ba] Flux v0.10.0
  [e5e0dc1b] Juno v0.7.2
  [5fb14364] OhMyREPL v0.5.3
  [295af30f] Revise v2.3.1
  [e88e6eb3] Zygote v0.4.1
```

CUDA: See above

**Additional context**
Full output when running tests:
https://gist.github.com/DrChainsaw/1dc5187245fa86a7888953430d931af2

**Comment by DrChainsaw** [comment]
Ok, I think I managed to sort things out.

The bad parameter was epsilon which defaulted to 1e-5. Using 1e-3 made the error go away. 

However, I did not need to change eps to 1e-3 due to this: 

My CUDA_PATH pointed to CUDA 10.0 which also was the latest version of CUDA I had installed. After installing CUDA 10.2 i still got the same error until I remembered that cuDNN needs to be downloaded separately. After downloading the latest cuDNN the error disappeared while keeping epsilon to 1e-5.
